### ISSUE TITLE
خارج شدن از صفحه سرچ هنگام تعوض صفحه

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#17]
وقتی یه رویدادی رو سرچ میکنیم، هنگامی که از صفحه ی سرچ به یک صفحه ی دیگه مثل نقشه یا 
پیام ها میریم، وقتی روی ایکون صفحه ی اصلی میزنیم وارد همون صفحه ی سرچ میشه.

**Comment by Ghaderi84** [comment]
انجام شد ۳۰ دقیقه
