### ISSUE TITLE
هنگامی که وارد صفحه نقشه میشویم پیشنهاد دهد که لوکیشن رو روشن کنیم

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#22]
هنگامی که وارد صفحه نقشه میشویم یه پاپ آپ باز شود و به کاربر پیشنهاد دهد که لوکیشن رو روشن کند تا رودادهای اطرافش را راحت تر پیدا کنید

**Comment by rajabianmohammad** [comment]
هنگامی که وارد صفحه نقشه میشویم یه پاپ آپ باز شود و به کاربر پیشنهاد دهد که لوکیشن رو روشن کند تا رودادهای اطرافش را راحت تر پیدا کنید.

**Comment by Ghaderi84** [comment]
انجام شد - ۴۵ دقیقه
