### ISSUE TITLE
عکس گذاشتن برای رویداد اجباری شود

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#23]
برای هر رویداد عکس گذاشتن اجباری شود در صورتی که کاربر عکس آپلود نکرد و از صفحه تعریف رویداد خارج شد، رویداد در بخش رویدادهای من نمایش داده شود ولی در صفحه ی اصلی و نقشه نشون داده نشه تا زمانی که رویدادش رو ویرایش کنه و براش عکس بزاره

**Comment by Ghaderi84** [comment]
انجام شد - ۲ ساعت
