### ISSUE TITLE
وقتی توی صفحه ی نقشه روی رویدادی کلیک میکنیم اندازه عکس خیلی کشیده هستش

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#30]
وقتی توی صفحه ی نقشه روی رویدادی کلیک میکنیم اندازه عکس خیلی کشیده هستش و جذابیت خود عکس به نظرم اصلا معلوم نمیشه خیلی از عکس ها هم ناقص میشن مثلا دو نفر کنار هم هستن سر یکیشون ازکادر خارج شده

**Comment by Ghaderi84** [comment]
تصحیح شد - این نوع عکس ها با پنل اضافه شده اند و پنل کنترل نکرده طول و عرض تصویر رو
زمان: 30 دقیقه
