### ISSUE TITLE
وقتی عنوان یک رویداد زیاد باشه فرم رویداد در صفحه اصلی بهم میخوره

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#32]
![Screenshot_20190828-121503_Paasho](https://user-images.githubusercontent.com/54270604/63842430-c8598500-c999-11e9-84df-cfac0b8a3d24.jpg)

وقتی کسی عنوانش بیشتر از یک خط میشه هم امتیاز رویداد (تعداد ستاره های رویداد) جابجا میشه و هم خط دومش نصفه میفته

باید هم شکل ظاهریش درست بشه و هم رویداد هنگام تعریف رویداد عنوان دلخواه شخص محدودیت کارکتر داشته باشه

**Comment by Ghaderi84** [comment]
انجام شد - این مشکل برای همه بخش هایی که عنوان رویداد رو نمایش میدهند وجود داره - نقشه، لیست رویدادهای من و ...

زمان انجام : 3 ساعت
