### ISSUE TITLE
در صفحه ی ویرایش رویداد وقتی رویداد رو ویرایش میکنیم با زدن تایید خارج شود

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#33]
در صفحه ی ویرایش رویداد وقتی ویرایش را انجام میدهیم با زدن دکمه ی تایید از صفحه ی ویرایش رویداد خارج شود و اعلام کند تغییرات ذخیره شد.

**Comment by Ghaderi84** [comment]
انجام اینکار درست نیست - امکان داره کاربر بخواد تغییرات دیگری انجام بده و یا عکس انتخاب کنه  - بهتره هر وقت خودش خواست خارج بشه
