### ISSUE TITLE
پریدن عکس رویداد وقتی کامنت تایپ میکنیم و بر خالی ماندن جای عکس رویداد

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#39]
پریدن عکس رویداد وقتی کامنت تایپ میکنیم و بر خالی ماندن جای عکس رویداد تا زمانی که صفحه رو عوض کنیم.

**Comment by Ghaderi84** [comment]
انجام شد - زمان 15 دقیقه
