### ISSUE TITLE
نشدن صفحه اصلی refresh

### ISSUE THREAD

**Issue by rajabianmohammad** [farzad-sedaghatbin/Paasho_Board#6]
در صفحه ی اصلی هنگامی که صفحه رو پایین میکشیم تا رفرش بشه صفحه
(می کنیم Push down)
میشه ولی عملا این اتفاق نمی افتهrefresh در ظاهر صفحه 
برای تست کردن این موضوع وقتی وارد یک رویداد میشید و برمیگردید تعدادبازدید هاش زیاد نمیشه حتی موقعی که صفحه را 
Push donw
میکنیدو وقتی روی تب پر طرفدار میزنید تازه رفرش میشه و تعداد بازدید ها زیاد میشه همچنین وقتی رویداد جدید تعریف میکنید توی صفحه ی پر طرفداد هرچقدر 
push down 
کنید نمیاد ولی وقتی روی تب پر طرفدار بزنید و صفحه رفرش بشه میاد

**Comment by Ghaderi84** [comment]
انجام شد -  ۳۰ دقیقه
